### ISSUE TITLE
Usage of boost::void_t

### ISSUE THREAD

**Issue by ax3l** [boostorg/type_traits#113]
Boost 1.67.0+ uses `boost::void_t<>` in many traits, although it is only defined if `BOOST_NO_CXX11_TEMPLATE_ALIASES` is not defined.

This causes compile issues on platforms using those includes where template aliases are not available (or `BOOST_NO_CXX11_TEMPLATE_ALIASES` is set).

**Comment by jzmaddock** [comment]
>This causes compile issues on platforms using those includes where template aliases are not available (or `BOOST_NO_CXX11_TEMPLATE_ALIASES` is set).

Is there a specific compiler configuration that's causing you problems?  Note that all the traits that use `void_t` do have workarounds in place for older compilers.

**Comment by ax3l** [comment]
I just saw it with an old work-around with nvcc. it's not like nvcc does not support template aliases, but we used the work-around to deactivate another issue for some time.

[`void_t`](https://github.com/boostorg/type_traits/blob/boost-1.67.0/include/boost/type_traits/make_void.hpp#L39-L46) has no fallback, but is used [in regular traits](https://github.com/boostorg/type_traits/blob/boost-1.67.0/include/boost/type_traits/has_minus.hpp#L55) since 1.67.0

**Comment by glenfe** [comment]
Any `void_t<X>` can be `typename make_void<X>::type` to support implementations that do not support C++11 template aliases.

**Comment by ax3l** [comment]
Yes, that's what I am suggesting: use `boost::make_void<>::type` in those places?

**Comment by glenfe** [comment]
Pull request #115

**Comment by jzmaddock** [comment]
Merged to develop.
