### ISSUE TITLE
compile error, boost_1_70_0_b1, C++17, MSVC 1916

### ISSUE THREAD

**Issue by Cry-Thomas** [boostorg/type_traits#118]
we found Boost version 1.70.0 b1 not compiling against our code base with C++17 and MSVC version 1916 in conjunction with the `/Zc:noexceptTypes-` compiler flag. Resulting error is of type:

```
boost\type_traits\detail\is_member_function_pointer_cxx_11.hpp(359): error C2953: 'boost::is_member_function_pointer<Ret(__cdecl C::* )(Args...)>': class template has already been defined
boost\type_traits\detail\is_member_function_pointer_cxx_11.hpp(48): note: see declaration of 'boost::is_member_function_pointer<Ret(__cdecl C::* )(Args...)>'
```

**Comment by Cry-Thomas** [comment]
we found Boost version 1.70.0 b1 not compiling against our code base with C++17 and MSVC version 1916 in conjunction with the `/Zc:noexceptTypes-` compiler flag. Resulting error is of type:

```
boost\type_traits\detail\is_member_function_pointer_cxx_11.hpp(359): error C2953: 'boost::is_member_function_pointer<Ret(__cdecl C::* )(Args...)>': class template has already been defined
boost\type_traits\detail\is_member_function_pointer_cxx_11.hpp(48): note: see declaration of 'boost::is_member_function_pointer<Ret(__cdecl C::* )(Args...)>'
```

**Comment by pdimov** [comment]
It's enough to `#include <boost/type_traits/is_function.hpp>` for the error to occur.

**Comment by jzmaddock** [comment]
I've just pushed a fix for this, but a temporary workaround is to add -DBOOST_TT_NO_NOEXCEPT_SEPARATE_TYPE to the command line.

**Comment by Cry-Thomas** [comment]
> 
> 
> I've just pushed a fix for this, but a temporary workaround is to add -DBOOST_TT_NO_NOEXCEPT_SEPARATE_TYPE to the command line.

Thanks for the swift action!

**Comment by pdimov** [comment]
MSVC 2017 also has its own macro for noexcept function types (`_NOEXCEPT_TYPES_SUPPORTED`), that predates their implementing the SD6 macros: https://github.com/boostorg/bind/commit/070185914d721e8bc67e9585f4a33b963d67b741

**Comment by jzmaddock** [comment]
>MSVC 2017 also has its own macro for noexcept function types (_NOEXCEPT_TYPES_SUPPORTED), that predates their implementing the SD6 macros: boostorg/bind@0701859

Thanks, support added.
