### ISSUE TITLE
Failures because of lack of CI_SUPPRESS_KNOWN_ISSUES

### ISSUE THREAD

**Issue by pdimov** [boostorg/type_traits#49]
I've enhanced the superproject Appveyor (and Travis) to run the tests for the library updated in the commit:

https://ci.appveyor.com/project/boostorg/boost/build/1.0.3623

But type_traits fails because - I assume - CI_SUPPRESS_KNOWN_ISSUES isn't set.

Since this Appveyor support is generic and not specific to a library, I'd rather not include library-specific workarounds in it such as this one; so maybe the test Jamfile could detect Appveyor and Travis using for example `[ os.environ CI ]` and turn on the workarounds automatically?

**Comment by jzmaddock** [comment]
I've pushed a fix for this, also for building multiple configurations per virtual machine, and we'll see how it goes.

**Comment by Flast** [comment]
OFF TOPIC: @pdimov did you advertize about `CI_SUPPRESS_KNOWN_ISSUES` anywhere? I suppose many developer don't know about it (incl. me).

**Comment by pdimov** [comment]
`CI_SUPPRESS_KNOWN_ISSUES` is a macro specific to TypeTraits's tests, defined by @jzmaddock here: https://github.com/boostorg/type_traits/blob/develop/test/Jamfile.v2#L12 and checked f.ex. here: https://github.com/boostorg/type_traits/blob/develop/test/tricky_rvalue_test.cpp#L22.

There's nothing for me to advertise, really, as I've had nothing to do with it. :-)

**Comment by Flast** [comment]
> CI_SUPPRESS_KNOWN_ISSUES is a macro specific to TypeTraits's tests

Ahhh, sorry I misunderstood that: I thought super-project defines it.
