### ISSUE TITLE
`is_final` doesn't work with template types on gcc 6.4.0

### ISSUE THREAD

**Issue by danieljames** [boostorg/type_traits#66]
For this code:

    #include <boost/type_traits/is_final.hpp>
    #include <type_traits>
    #include <iostream>

    struct final1 final {};
    template <typename T> struct final2 final {};

    int main() {
        std::cout << "boost::is_final<final1>: " << boost::is_final<final1>::value << std::endl;
        std::cout << "boost::is_final<final2<int>>::value: " << boost::is_final<final2<int>>::value << std::endl;
        std::cout << "std::is_final<final1>: " << std::is_final<final1>::value << std::endl;
        std::cout << "std::is_final<final2<int>>::value: " << std::is_final<final2<int>>::value << std::endl;
    }

GCC 6.4.0 outputs:

    boost::is_final<final1>: 1
    boost::is_final<final2<int>>::value: 0
    std::is_final<final1>: 1
    std::is_final<final2<int>>::value: 1

I'd expect all values to be `1`. I get that for Clang.

**Comment by Lastique** [comment]
The test fails with gcc 7.2 as well. This is weird, `std::is_final` is defined the same way as `boost::is_final`, only without `remove_cv`. Removing `remove_cv` doesn't fix it. `__is_final` intrinsic reports the correct result all the time. Looks like a compiler bug to me.

**Comment by Lastique** [comment]
Nevermind that, I'm failing miserably today for some reason.

Removing `remove_cv` *does* fix the problem for gcc 6 and 7.

**Comment by jzmaddock** [comment]
This should be fixed in develop now.
