### ISSUE TITLE
Missing #pragma warning(pop) on MSVC?

### ISSUE THREAD

**Issue by mehrdadn** [boostorg/type_traits#68]
It seems there might be some unmatched warning pushes/pops on Visual C++ [here](/boostorg/type_traits/blob/fb4430512d26681a7b06c434c793f98567a8ad4a/include/boost/type_traits/has_plus_assign.hpp#L30) and [here](/boostorg/type_traits/blob/e4d3cba6dd65d54e40751ed1e336cdd761620682/include/boost/type_traits/has_minus.hpp#L30).
Note that there may be more—these are only the ones I've noticed.

**Comment by jzmaddock** [comment]
Good catch: now fixed in develop, thanks!

**Comment by robhouse** [comment]
@jzmaddock - I believe the new #if block in has_minus.hpp should have been inserted after the next #endif. The same appears true for has_minus_assign.hpp and has_plus_assign.hpp as well.

**Comment by jzmaddock** [comment]
Yep, fixed now - thanks!
