### ISSUE TITLE
Has move ctor/assign intrinsics are absent on any version of clang

### ISSUE THREAD

**Issue by Flast** [boostorg/type_traits#73]
`__has_feature` and `__has_builtin` on clang don't help to detect move ctor/assing checking intrinsic, see https://wandbox.org/permlink/PagEil6PmRSgjELM , thus `boost::has_trivial_move_*` don't work...

Both of the intrinsics are introduced on clang 3.3 release, so I'm trying to detect those via other feature.

**Comment by jzmaddock** [comment]
Testing a fix in https://github.com/boostorg/type_traits/pull/74

**Comment by jzmaddock** [comment]
This should be addressed in develop now.
