### ISSUE TITLE
Unbalanced pragma warning( push/pop )

### ISSUE THREAD

**Issue by PG-Devs** [boostorg/type_traits#91]
In include/boost/type_traits/is_virtual_base_of.hpp

![is_virtual_base_of patch](https://user-images.githubusercontent.com/22977594/45557659-66fadd80-b83e-11e8-8e1b-653db95830fe.gif)
(rename to .patch)

**Comment by Olipro** [comment]
Why would you do this? Make a pull request, or if you don't know how to use git, put it in a pastebin (GitHub has one, there's various others). There are a myriad of options considerably less ridiculous than uploading a patch as a gif.

**Comment by PG-Devs** [comment]
It's good with you man
