### ISSUE TITLE
error: class template partial specialization contains a template parameter that cannot be deduced;

### ISSUE THREAD

**Issue by viboes** [boostorg/type_traits#93]
```
error: class template partial specialization contains a template parameter that cannot be deduced; this partial specialization will never be used [-Wunusable-partial-specialization]
   struct is_function<Ret BOOST_TT_DEF_CALL(Args...)BOOST_TT_NOEXCEPT_DECL> : public true_type {};
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

See https://circleci.com/gh/boostorg/thread/520

**Comment by pdimov** [comment]
This continues to be an issue on f.ex. xcode9.1: https://travis-ci.org/boostorg/fiber/jobs/475698007

I don't know why the Type Traits tests don't catch it (apart from not having xcode9.1) - the error is probably issued by Clang 6 or 7, whereas the Travis matrix only goes to 5 at the moment.

**Comment by jzmaddock** [comment]
This passes with 9.4 (https://travis-ci.org/boostorg/type_traits/builds/475930539?utm_source=github_status&utm_medium=notification), will add a 9.1 test as well and we'll see.

**Comment by jzmaddock** [comment]
Fixed in develop.
